// <auto-generated />
namespace Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class membername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(membername));
        
        string IMigrationMetadata.Id
        {
            get { return "202306111634494_member-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
