// <auto-generated />
namespace Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class review1m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(review1m));
        
        string IMigrationMetadata.Id
        {
            get { return "202306060132581_review-1-m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
